import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T17:19:17.338Z
// Duration (active): 136764ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "See options" })
    await page.locator("#hlc-see-options").click();
    // submit on locator("#hlc-inputs")
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").click();
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(2)").click();
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "See options" })
    await page.locator("#hlc-see-options").click();
    // submit on locator("#hlc-inputs")
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").click();
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").click();
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").click();
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").click();
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").click();
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").click();
    // idle 8995ms (no stable next locator — consider a manual waitFor)
    // idle 10015ms (no stable next locator — consider a manual waitFor)
    // idle 7988ms (no stable next locator — consider a manual waitFor)
    // idle 8013ms (no stable next locator — consider a manual waitFor)
  });
});
