import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T14:48:26.950Z
// Duration (active): 322262ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > details > summary").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > details > summary").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > details > summary").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > details > summary").click();
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > p").click();
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > details > summary").waitFor({ state: 'visible' });
    await page.locator("footer > div > div:nth-of-type(2) > div > section > div > details > summary").click();
    await page.locator("html").waitFor({ state: 'visible' });
    await page.locator("html").waitFor({ state: 'visible' });
    await page.locator("html").click();
  });
});
