import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T18:25:24.871Z
// Duration (active): 556790ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(2) > strong").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(2) > strong").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(2) > strong").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(2) > strong").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(2) > strong").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how loan amount for Bank of Maharashtra was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1)").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(2) > div > div:nth-of-type(1)").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > span:nth-of-type(2)").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(5) > div > div:nth-of-type(1) > span:nth-of-type(2)").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > span:nth-of-type(1)").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(3) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(3) > span:nth-of-type(1)").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how emi for Bank of Maharashtra was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(2) > div > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(2) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(2) > div > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(2) > span:nth-of-type(1)").click();
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Close" })
    await page.locator("#hlc-drawer-close").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how emi for Bank of Maharashtra was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how loan amount for Bank of Maharashtra was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("button#hlc-show-more > span").waitFor({ state: 'visible' });
    await page.locator("button#hlc-show-more > span").click();
    await page.locator("#hlc-freshness-note").waitFor({ state: 'visible' });
    await page.locator("#hlc-freshness-note").waitFor({ state: 'visible' });
    await page.locator("#hlc-freshness-note").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div").click();
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(1)").click();
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").click();
    await page.locator("main").waitFor({ state: 'visible' });
    // fallback: getByRole("main")
    await page.locator("main").click();
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("tab", { name: "Charges" })
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").click();
    await page.locator("th#hlc-th-processingFee > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-processingFee > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-processingFee > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Open note for mark *" })
    await page.locator("th#hlc-th-processingFee > button").click();
    await page.locator("details#hlc-charge-note-processing-fees > summary").click();
    await page.locator("th#hlc-th-processingFee > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-processingFee > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-processingFee > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-processingFee > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-processingFee > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-processingFee > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-processingFee > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Open note for mark *" })
    await page.locator("th#hlc-th-processingFee > button").click();
    await page.locator("#hlc-th-processingFee").click();
    await page.locator("#hlc-th-processingFee").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-processingFee").click();
    await page.locator("#hlc-th-processingFee").click();
    // fallback: getByRole("button", { name: "Open note for mark *" })
    await page.locator("th#hlc-th-processingFee > button").click();
    await page.locator("details#hlc-charge-note-processing-fees > summary").click();
    await page.locator("th#hlc-th-processingFee > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Open note for mark *" })
    await page.locator("th#hlc-th-processingFee > button").click();
    // fallback: getByRole("button", { name: "Open note for mark *" })
    await page.locator("th#hlc-th-processingFee > button").click();
    await page.locator("#hlc-th-processingFee").click();
    await page.locator("th#hlc-th-processingFee > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Open note for mark *" })
    await page.locator("th#hlc-th-processingFee > button").click();
    await page.locator("details#hlc-charge-note-processing-fees > summary").click();
    await page.locator("th#hlc-th-propertyCheckCharges > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Open note for mark *" })
    await page.locator("th#hlc-th-propertyCheckCharges > button").click();
    await page.locator("details#hlc-charge-note-property-check-charges > summary").click();
    await page.locator("th#hlc-th-governmentCharges > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Open note for mark ^" })
    await page.locator("th#hlc-th-governmentCharges > button").click();
    await page.locator("details#hlc-charge-note-government-charges > summary").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how processing fees for Indian Bank was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(2) > button").click();
    // idle 8242ms (no stable next locator — consider a manual waitFor)
  });
});
