import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T18:11:25.578Z
// Duration (active): 574290ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span > span").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > div > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > div > div > div:nth-of-type(2) > span:nth-of-type(2)").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(3) > summary > span > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(3) > summary > span > span").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(4) > summary > span > svg > path").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(4) > summary > span > svg > path").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(5) > summary > span > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(5) > summary > span > span").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(5) > summary > span > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(5) > summary > span > span").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(4) > summary > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(4) > summary > span").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(3) > summary > span > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(3) > summary > span > span").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(1)").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how loan amount for Bank of Maharashtra was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "More about Bank of Maharashtra" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span > svg").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how loan amount for Bank of Maharashtra was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how emi for Bank of Maharashtra was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(1) > span").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(1) > span").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg > path").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg > path").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how loan amount for Bank of Maharashtra was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how loan amount for Bank of Maharashtra was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > span:nth-of-type(2)").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3) > div > div:nth-of-type(4) > span:nth-of-type(2)").click();
    // idle 9873ms (no stable next locator — consider a manual waitFor)
    // idle 7999ms (no stable next locator — consider a manual waitFor)
    // idle 8008ms (no stable next locator — consider a manual waitFor)
    // idle 7995ms (no stable next locator — consider a manual waitFor)
    // idle 9973ms (no stable next locator — consider a manual waitFor)
    // idle 10025ms (no stable next locator — consider a manual waitFor)
  });
});
