import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T17:10:04.687Z
// Duration (active): 545586ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "See options" })
    await page.locator("#hlc-see-options").click();
    // submit on locator("#hlc-inputs")
    await page.locator("#hlc-age").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Age*\n                          \n                        \n                       " })
    // fallback: getByLabel("Age*\n                          \n                        \n                       ")
    // fallback: getByPlaceholder("35")
    await page.locator("#hlc-age").click();
    await page.locator("#hlc-age").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Age*\n                          \n                        \n                       " })
    // fallback: getByLabel("Age*\n                          \n                        \n                       ")
    // fallback: getByPlaceholder("35")
    await page.locator("#hlc-age").fill("35");
    await page.locator("#hlc-age").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Age*\n                          \n                        \n                       " })
    // fallback: getByLabel("Age*\n                          \n                        \n                       ")
    // fallback: getByPlaceholder("35")
    await page.locator("#hlc-age").fill("35");
    // fallback: getByRole("button", { name: "See options" })
    await page.locator("#hlc-see-options").click();
    // submit on locator("#hlc-inputs")
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "See options" })
    await page.locator("#hlc-see-options").click();
    // submit on locator("#hlc-inputs")
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").click();
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").click();
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "See options" })
    await page.locator("#hlc-see-options").click();
    // submit on locator("#hlc-inputs")
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").click();
    await page.locator("#hlc-existing-emis").waitFor({ state: 'visible' });
    await page.locator("#hlc-existing-emis").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Existing EMIs\n                          \n                        \n              " })
    // fallback: getByLabel("Existing EMIs\n                          \n                        \n              ")
    await page.locator("#hlc-existing-emis").click();
    await page.locator("#hlc-existing-emis").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Existing EMIs\n                          \n                        \n              " })
    // fallback: getByLabel("Existing EMIs\n                          \n                        \n              ")
    await page.locator("#hlc-existing-emis").fill("0");
    await page.locator("#hlc-existing-emis").press("Backspace");
    // fallback: getByRole("textbox", { name: "Existing EMIs\n                          \n                        \n              " })
    // fallback: getByLabel("Existing EMIs\n                          \n                        \n              ")
    await page.locator("#hlc-existing-emis").fill("");
    await page.locator("#hlc-existing-emis").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Existing EMIs\n                          \n                        \n              " })
    // fallback: getByLabel("Existing EMIs\n                          \n                        \n              ")
    await page.locator("#hlc-existing-emis").fill("555");
    await page.locator("#hlc-existing-emis").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Existing EMIs\n                          \n                        \n              " })
    // fallback: getByLabel("Existing EMIs\n                          \n                        \n              ")
    await page.locator("#hlc-existing-emis").fill("555");
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").click();
    // idle 9782ms (no stable next locator — consider a manual waitFor)
    // idle 10001ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 7994ms (no stable next locator — consider a manual waitFor)
  });
});
