import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T16:04:29.489Z
// Duration (active): 335368ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    // fallback: getByRole("tab", { name: "Other charges" })
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").click();
    await page.locator("th#hlc-th-prepaymentChargeDisplay > span > select").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Prepayment method" })
    await page.locator("th#hlc-th-prepaymentChargeDisplay > span > select").click();
    await page.locator("th#hlc-th-prepaymentChargeDisplay > span > select").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Prepayment method" })
    await page.locator("th#hlc-th-prepaymentChargeDisplay > span > select").fill("balanceTransfer");
    await page.locator("th#hlc-th-prepaymentChargeDisplay > span > select").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Prepayment method" })
    await page.locator("th#hlc-th-prepaymentChargeDisplay > span > select").click();
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("tab", { name: "Overview" })
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(1)").click();
    // idle 8719ms (no stable next locator — consider a manual waitFor)
  });
});
