import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T17:34:55.529Z
// Duration (active): 533319ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Monthly income*\n                        \n                      \n                " })
    // fallback: getByLabel("Monthly income*\n                        \n                      \n                ")
    // fallback: getByPlaceholder("1,00,000")
    await page.locator("#hlc-monthly-income").click();
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Monthly income*\n                        \n                      \n                " })
    // fallback: getByLabel("Monthly income*\n                        \n                      \n                ")
    // fallback: getByPlaceholder("1,00,000")
    await page.locator("#hlc-monthly-income").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    // fallback: getByRole("textbox", { name: "Age*\n                          \n                        \n                       " })
    // fallback: getByLabel("Age*\n                          \n                        \n                       ")
    // fallback: getByPlaceholder("35")
    await page.locator("#hlc-age").click();
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    // fallback: getByRole("button", { name: "Salaried" })
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(1)").click();
    // fallback: getByRole("button", { name: "Top-up" })
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > div > button:nth-of-type(2)").click();
    await page.locator("#hlc-foir").waitFor({ state: 'visible' });
    await page.locator("#hlc-foir").waitFor({ state: 'visible' });
    await page.locator("#hlc-foir").waitFor({ state: 'visible' });
    await page.locator("#hlc-foir").waitFor({ state: 'visible' });
    await page.locator("#hlc-foir").waitFor({ state: 'visible' });
    await page.locator("#hlc-foir").waitFor({ state: 'visible' });
    await page.locator("#hlc-foir").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Share of income for EMIs /FOIR\n                          \n                      " })
    // fallback: getByLabel("Share of income for EMIs /FOIR\n                          \n                      ")
    await page.locator("#hlc-foir").click();
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Yes" })
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").click();
    await page.locator("#hlc-coapplicant").fill("yes");
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").click();
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").click();
    await page.locator("#hlc-foir").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Share of income for EMIs /FOIR\n                          \n                      " })
    // fallback: getByLabel("Share of income for EMIs /FOIR\n                          \n                      ")
    await page.locator("#hlc-foir").click();
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Monthly income*\n                        \n                      \n                " })
    // fallback: getByLabel("Monthly income*\n                        \n                      \n                ")
    // fallback: getByPlaceholder("1,00,000")
    await page.locator("#hlc-monthly-income").click();
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("tab", { name: "Overview" })
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(1)").click();
    await page.locator("main > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > div > div").click();
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Monthly income*\n                        \n                      \n                " })
    // fallback: getByLabel("Monthly income*\n                        \n                      \n                ")
    // fallback: getByPlaceholder("1,00,000")
    await page.locator("#hlc-monthly-income").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    // idle 8291ms (no stable next locator — consider a manual waitFor)
    // idle 10004ms (no stable next locator — consider a manual waitFor)
  });
});
