import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T14:21:00.929Z
// Duration (active): 511586ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(2)").click();
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(2)").click();
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    await page.locator("#home-lead-title").waitFor({ state: 'visible' });
    // fallback: getByRole("heading")
    await page.locator("#home-lead-title").click();
    // idle 8263ms (no stable next locator — consider a manual waitFor)
    // idle 8007ms (no stable next locator — consider a manual waitFor)
    // idle 9994ms (no stable next locator — consider a manual waitFor)
    // idle 9983ms (no stable next locator — consider a manual waitFor)
    // idle 8003ms (no stable next locator — consider a manual waitFor)
    // idle 8001ms (no stable next locator — consider a manual waitFor)
    // idle 10017ms (no stable next locator — consider a manual waitFor)
    // idle 8002ms (no stable next locator — consider a manual waitFor)
    // idle 8002ms (no stable next locator — consider a manual waitFor)
    // idle 9995ms (no stable next locator — consider a manual waitFor)
  });
});
