import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T18:43:33.349Z
// Duration (active): 564971ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("tab", { name: "Charges" })
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(14) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how property check charges for State Bank of India was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(14) > td:nth-of-type(3) > button").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(20) > td:nth-of-type(4) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(20) > td:nth-of-type(4) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(20) > td:nth-of-type(4) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how government charges for HDFC Bank was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(20) > td:nth-of-type(4) > button").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("#hlc-th-governmentCharges").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-governmentCharges").click();
    // fallback: getByRole("button", { name: "Open note for mark ^" })
    await page.locator("th#hlc-th-governmentCharges > button").click();
    await page.locator("details#hlc-charge-note-government-charges > summary").click();
    await page.locator("details#hlc-charge-note-government-charges > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-government-charges > summary > span > svg").click();
    await page.locator("details#hlc-charge-note-government-charges > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-government-charges > summary > span > svg").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(4) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(4) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how government charges for Yes Bank was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(4) > button").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(2) > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(2) > p > span:nth-of-type(2)").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(3)").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(4) > p:nth-of-type(1)").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(2) > strong").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(2) > strong").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(2) > strong").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    // fallback: getByRole("tab", { name: "Other charges" })
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").click();
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Rate change type" })
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").click();
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Rate change type" })
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").fill("repricing");
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Rate change type" })
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").click();
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Rate change type" })
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").fill("benchmark");
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Rate change type" })
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").click();
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Rate change type" })
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").fill("typeSwitch");
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Rate change type" })
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").click();
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Rate change type" })
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").fill("repricing");
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Rate change type" })
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").click();
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").waitFor({ state: 'visible' });
    // fallback: getByRole("combobox", { name: "Rate change type" })
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > select").fill("benchmark");
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Open note for mark °" })
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").click();
    await page.locator("details#hlc-charge-note-rate-change-charge > summary").click();
    await page.locator("details#hlc-charge-note-prepayment-charge > summary > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-prepayment-charge > summary > span").click();
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").click();
    await page.locator("th#hlc-th-overdueChargeDisplay > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-overdueChargeDisplay > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-overdueChargeDisplay > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-overdueChargeDisplay > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-overdueChargeDisplay > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-overdueChargeDisplay > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-overdueChargeDisplay > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-overdueChargeDisplay > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-overdueChargeDisplay > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-overdueChargeDisplay > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-overdueChargeDisplay > button").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-overdueChargeDisplay > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Open note for mark ‡" })
    await page.locator("th#hlc-th-overdueChargeDisplay > button").click();
    await page.locator("details#hlc-charge-note-overdue-charge > summary").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(30) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(30) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(30) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(30) > td:nth-of-type(4) > span > span").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(29) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(29) > td:nth-of-type(4) > span > span").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(29) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(29) > td:nth-of-type(4) > span > span").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(30) > td:nth-of-type(4) > span > span").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(15) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(15) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(15) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(15) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(15) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(15) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(15) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(15) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(15) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(15) > td:nth-of-type(4) > span > span").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(15) > td:nth-of-type(4) > span > span").click();
    // idle 8369ms (no stable next locator — consider a manual waitFor)
  });
});
