import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T15:36:22.615Z
// Duration (active): 541971ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("main > section:nth-of-type(1) > div > div > a").waitFor({ state: 'visible' });
    // fallback: getByRole("link", { name: "Explore banks" })
    await Promise.all([
      page.waitForURL("http://localhost:8765/pages/explore-banks.html"),
      page.locator("main > section:nth-of-type(1) > div > div > a").click(),
    ]);
    // unknown event kind: landmark_snapshot
    // idle 6803ms (no stable next locator — consider a manual waitFor)
    await page.keyboard.press("Meta+Meta");
    await page.keyboard.press("Meta+Shift+Shift");
    await page.keyboard.press("Meta+Shift+r");
    // unknown event kind: landmark_snapshot
    // idle 1241ms (no stable next locator — consider a manual waitFor)
    // idle 2810ms (no stable next locator — consider a manual waitFor)
    await page.goto("http://localhost:8765/");
    await page.screenshot({ path: "screenshots/root.png" });
    await page.locator("main > section:nth-of-type(1) > div > div > a").waitFor({ state: 'visible' });
    // unknown event kind: landmark_snapshot
    await page.locator("main > section:nth-of-type(1) > div > div > a").waitFor({ state: 'visible' });
    // fallback: getByRole("link", { name: "Explore banks" })
    await Promise.all([
      page.waitForURL("http://localhost:8765/pages/explore-banks.html"),
      page.locator("main > section:nth-of-type(1) > div > div > a").click(),
    ]);
    // unknown event kind: landmark_snapshot
    await page.locator("main > div").waitFor({ state: 'visible' });
    await page.locator("main > div").waitFor({ state: 'visible' });
    await page.locator("main > div").click();
    await page.locator("#hlc-age").waitFor({ state: 'visible' });
    await page.locator("#hlc-age").waitFor({ state: 'visible' });
    await page.locator("#hlc-age").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Age*\n                          \n                        \n                       " })
    // fallback: getByLabel("Age*\n                          \n                        \n                       ")
    // fallback: getByPlaceholder("35")
    await page.locator("#hlc-age").click();
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-see-options").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "See options" })
    await page.locator("#hlc-see-options").click();
    // submit on locator("#hlc-inputs")
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Public" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Private" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(3)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Public" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").click();
    // fallback: getByRole("button", { name: "Private" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(3)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "All" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(1)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Public" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").click();
    // fallback: getByRole("button", { name: "Private" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(3)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Public" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").click();
    // fallback: getByRole("button", { name: "Private" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(3)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "All" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(1)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Public" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").click();
    // fallback: getByRole("button", { name: "All" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(1)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "All" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(1)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Public" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(2)").click();
    // fallback: getByRole("button", { name: "Private" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(3)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "All" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(1)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(4) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(4) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Fixed\n                      About 1–2% higher" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(4) > div > button:nth-of-type(2)").click();
    // fallback: getByRole("button", { name: "Floating" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(4) > div > button:nth-of-type(1)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(5) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Term loan" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(5) > div > button:nth-of-type(1)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(5) > div > button:nth-of-type(2) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(5) > div > button:nth-of-type(2) > span:nth-of-type(1)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(5) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Term loan" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(5) > div > button:nth-of-type(1)").click();
    await page.locator("legend#hlc-borrower-label > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-borrower-label > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-borrower-label > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-borrower-label > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-borrower-label > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-borrower-label > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-borrower-label > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-borrower-label > span > span:nth-of-type(2) > button > span > svg > rect").click();
    await page.locator("legend#hlc-borrower-label > span > span:nth-of-type(2) > button > span > svg > rect").click();
    await page.locator("legend#hlc-borrower-label > span > span:nth-of-type(2) > button > span > svg > rect").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(2)").click();
    await page.locator("legend#hlc-borrower-label > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-borrower-label > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(2)").click();
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("#hlc-filters-panel").waitFor({ state: 'visible' });
    // fallback: getByRole("region", { name: "Filters" })
    await page.locator("#hlc-filters-panel").click();
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > rect").click();
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > rect").click();
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("legend#hlc-concessions-label > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(2)").click();
    await page.locator("div#hlc-help-concessions > a").waitFor({ state: 'visible' });
    // fallback: getByRole("link", { name: "Learn more" })
    await Promise.all([
      page.waitForURL("http://localhost:8765/pages/concessions.html#bank-rates"),
      page.locator("div#hlc-help-concessions > a").click(),
    ]);
    // unknown event kind: landmark_snapshot
    await page.locator("section#bank-rates > div > div > ul > li:nth-of-type(3) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#bank-rates > div > div > ul > li:nth-of-type(3) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#bank-rates > div > div > ul > li:nth-of-type(3) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#bank-rates > div > div > ul > li:nth-of-type(3) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#bank-rates > div > div > ul > li:nth-of-type(3) > span:nth-of-type(2)").click();
    await page.locator("#guide-swap").waitFor({ state: 'visible' });
    await page.locator("#guide-swap").waitFor({ state: 'visible' });
    await page.locator("#guide-swap").click();
    await page.locator("div#guide-swap > header").waitFor({ state: 'visible' });
    await page.locator("div#guide-swap > header").waitFor({ state: 'visible' });
    await page.locator("div#guide-swap > header").waitFor({ state: 'visible' });
    // fallback: getByRole("banner")
    await page.locator("div#guide-swap > header").click();
    // idle 2785ms (no stable next locator — consider a manual waitFor)
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/explore-banks-html.png" });
    // idle 8279ms (no stable next locator — consider a manual waitFor)
    // idle 7999ms (no stable next locator — consider a manual waitFor)
    // idle 10022ms (no stable next locator — consider a manual waitFor)
    // idle 7993ms (no stable next locator — consider a manual waitFor)
    // idle 8006ms (no stable next locator — consider a manual waitFor)
    // idle 8005ms (no stable next locator — consider a manual waitFor)
    // idle 7986ms (no stable next locator — consider a manual waitFor)
    // idle 7985ms (no stable next locator — consider a manual waitFor)
    // idle 10001ms (no stable next locator — consider a manual waitFor)
    // idle 8029ms (no stable next locator — consider a manual waitFor)
    // idle 7983ms (no stable next locator — consider a manual waitFor)
    // idle 10006ms (no stable next locator — consider a manual waitFor)
    // idle 7990ms (no stable next locator — consider a manual waitFor)
    // idle 9995ms (no stable next locator — consider a manual waitFor)
    // idle 7989ms (no stable next locator — consider a manual waitFor)
    // idle 7988ms (no stable next locator — consider a manual waitFor)
    // idle 8012ms (no stable next locator — consider a manual waitFor)
    // idle 9979ms (no stable next locator — consider a manual waitFor)
    // idle 8009ms (no stable next locator — consider a manual waitFor)
    // idle 10010ms (no stable next locator — consider a manual waitFor)
    // idle 10009ms (no stable next locator — consider a manual waitFor)
    // idle 9952ms (no stable next locator — consider a manual waitFor)
  });
});
