import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T18:34:46.547Z
// Duration (active): 523772ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("th#hlc-th-processingFee > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Open note for mark *" })
    await page.locator("th#hlc-th-processingFee > button").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how property check charges for Indian Bank was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(3) > button").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div > span:nth-of-type(2)").click();
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Close" })
    await page.locator("#hlc-drawer-close").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(5) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how processing fees for Canara Bank was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(5) > td:nth-of-type(2) > button").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(2) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(2) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(2) > div > div:nth-of-type(2) > span:nth-of-type(2)").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(2) > div > div:nth-of-type(3)").click();
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Close" })
    await page.locator("#hlc-drawer-close").click();
    await page.locator("th#hlc-th-processingFee > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Open note for mark *" })
    await page.locator("th#hlc-th-processingFee > button").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(29) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(29) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(29) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how processing fees for DCB Bank was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(29) > td:nth-of-type(2) > button").click();
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > div:nth-of-type(1) > div:nth-of-type(1) > div > div:nth-of-type(2) > span:nth-of-type(2)").click();
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Close" })
    await page.locator("#hlc-drawer-close").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(2) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how processing fees for IDFC FIRST Bank was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(2) > button").click();
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Close" })
    await page.locator("#hlc-drawer-close").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(14) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how property check charges for State Bank of India was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(14) > td:nth-of-type(3) > button").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(11) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(11) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(11) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how property check charges for Punjab & Sind Bank was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(11) > td:nth-of-type(3) > button").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("tab", { name: "Overview" })
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(1)").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(11) > td:nth-of-type(3) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how loan amount for Punjab & Sind Bank was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(11) > td:nth-of-type(3) > button").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
  });
});
