import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T17:32:34.848Z
// Duration (active): 121662ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").click();
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").click();
    await page.locator("#hlc-existing-emis").waitFor({ state: 'visible' });
    await page.locator("#hlc-existing-emis").waitFor({ state: 'visible' });
    await page.locator("#hlc-existing-emis").waitFor({ state: 'visible' });
    await page.locator("#hlc-existing-emis").waitFor({ state: 'visible' });
    await page.locator("#hlc-existing-emis").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Existing EMIs\n                          \n                        \n              " })
    // fallback: getByLabel("Existing EMIs\n                          \n                        \n              ")
    await page.locator("#hlc-existing-emis").click();
    // fallback: getByRole("textbox", { name: "Existing EMIs\n                          \n                        \n              " })
    // fallback: getByLabel("Existing EMIs\n                          \n                        \n              ")
    await page.locator("#hlc-existing-emis").click();
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > svg").click();
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1)").click();
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Yes" })
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(2)").click();
    await page.locator("#hlc-coapplicant").fill("yes");
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "No" })
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(1)").click();
    await page.locator("#hlc-coapplicant").fill("no");
    // idle 7368ms (no stable next locator — consider a manual waitFor)
    // idle 7995ms (no stable next locator — consider a manual waitFor)
  });
});
