import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T18:59:02.434Z
// Duration (active): 146263ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // idle 7649ms (no stable next locator — consider a manual waitFor)
    // idle 6319ms (no stable next locator — consider a manual waitFor)
    // idle 3249ms (no stable next locator — consider a manual waitFor)
    // idle 4766ms (no stable next locator — consider a manual waitFor)
    // idle 5134ms (no stable next locator — consider a manual waitFor)
    // idle 2827ms (no stable next locator — consider a manual waitFor)
    // idle 8026ms (no stable next locator — consider a manual waitFor)
    // idle 7998ms (no stable next locator — consider a manual waitFor)
    // idle 4882ms (no stable next locator — consider a manual waitFor)
    // idle 1299ms (no stable next locator — consider a manual waitFor)
    // idle 3820ms (no stable next locator — consider a manual waitFor)
    // idle 7081ms (no stable next locator — consider a manual waitFor)
    // idle 6158ms (no stable next locator — consider a manual waitFor)
    // idle 1203ms (no stable next locator — consider a manual waitFor)
    // idle 1882ms (no stable next locator — consider a manual waitFor)
    // idle 1565ms (no stable next locator — consider a manual waitFor)
    // idle 6551ms (no stable next locator — consider a manual waitFor)
    // idle 4082ms (no stable next locator — consider a manual waitFor)
    // idle 3910ms (no stable next locator — consider a manual waitFor)
    // idle 3326ms (no stable next locator — consider a manual waitFor)
    // idle 3963ms (no stable next locator — consider a manual waitFor)
    // idle 1809ms (no stable next locator — consider a manual waitFor)
    // idle 5464ms (no stable next locator — consider a manual waitFor)
    // idle 2015ms (no stable next locator — consider a manual waitFor)
    // idle 3252ms (no stable next locator — consider a manual waitFor)
    // idle 4751ms (no stable next locator — consider a manual waitFor)
    // idle 6914ms (no stable next locator — consider a manual waitFor)
    // idle 1102ms (no stable next locator — consider a manual waitFor)
    // idle 1026ms (no stable next locator — consider a manual waitFor)
    // idle 9096ms (no stable next locator — consider a manual waitFor)
    // idle 3336ms (no stable next locator — consider a manual waitFor)
  });
});
