import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T15:46:08.706Z
// Duration (active): 541815ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "All" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(3) > div > button:nth-of-type(1)").click();
    await page.locator("main > div > header > h1 > span").waitFor({ state: 'visible' });
    await page.locator("main > div > header > h1 > span").waitFor({ state: 'visible' });
    await page.locator("main > div > header > h1 > span").waitFor({ state: 'visible' });
    await page.locator("main > div > header > h1 > span").waitFor({ state: 'visible' });
    await page.locator("main > div > header > h1 > span").waitFor({ state: 'visible' });
    await page.locator("main > div > header > h1 > span").waitFor({ state: 'visible' });
    await page.locator("main > div > header > h1 > span").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(2)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(2)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(2)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(1) > label > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > rect").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > rect").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("main > div").waitFor({ state: 'visible' });
    await page.locator("main > div").waitFor({ state: 'visible' });
    await page.locator("main > div").waitFor({ state: 'visible' });
    await page.locator("main > div").waitFor({ state: 'visible' });
    await page.locator("main > div").waitFor({ state: 'visible' });
    await page.locator("main > div").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(2)").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(2)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > rect").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(2) > label > span:nth-of-type(1) > span").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(1) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(1) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(1) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(1) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(1) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(1) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
  });
});
