import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T16:34:11.754Z
// Duration (active): 119080ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Monthly income*\n                        \n                      \n                " })
    // fallback: getByLabel("Monthly income*\n                        \n                      \n                ")
    // fallback: getByPlaceholder("1,00,000")
    await page.locator("#hlc-monthly-income").click();
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").press("Backspace");
    await page.locator("#hlc-monthly-income").press("Backspace");
    await page.locator("#hlc-monthly-income").press("Backspace");
    await page.locator("#hlc-monthly-income").press("Backspace");
    await page.locator("#hlc-monthly-income").press("Backspace");
    // fallback: getByRole("textbox", { name: "Monthly income*\n                        \n                      \n                " })
    // fallback: getByLabel("Monthly income*\n                        \n                      \n                ")
    // fallback: getByPlaceholder("1,00,000")
    await page.locator("#hlc-monthly-income").fill("");
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Monthly income*\n                        \n                      \n                " })
    // fallback: getByLabel("Monthly income*\n                        \n                      \n                ")
    // fallback: getByPlaceholder("1,00,000")
    await page.locator("#hlc-monthly-income").fill("1,00,000");
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Monthly income*\n                        \n                      \n                " })
    // fallback: getByLabel("Monthly income*\n                        \n                      \n                ")
    // fallback: getByPlaceholder("1,00,000")
    await page.locator("#hlc-monthly-income").fill("1,00,000");
    // fallback: getByRole("main")
    await page.locator("main").click();
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Monthly income*\n                        \n                      \n                " })
    // fallback: getByLabel("Monthly income*\n                        \n                      \n                ")
    // fallback: getByPlaceholder("1,00,000")
    await page.locator("#hlc-monthly-income").click();
    // fallback: getByRole("textbox", { name: "Monthly income*\n                        \n                      \n                " })
    // fallback: getByLabel("Monthly income*\n                        \n                      \n                ")
    // fallback: getByPlaceholder("1,00,000")
    await page.locator("#hlc-monthly-income").click();
    // fallback: getByRole("textbox", { name: "Monthly income*\n                        \n                      \n                " })
    // fallback: getByLabel("Monthly income*\n                        \n                      \n                ")
    // fallback: getByPlaceholder("1,00,000")
    await page.locator("#hlc-monthly-income").click();
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    // fallback: getByRole("main")
    await page.locator("main").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-age").waitFor({ state: 'visible' });
    await page.locator("#hlc-age").waitFor({ state: 'visible' });
    await page.locator("#hlc-age").waitFor({ state: 'visible' });
    await page.locator("#hlc-age").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Age*\n                          \n                        \n                       " })
    // fallback: getByLabel("Age*\n                          \n                        \n                       ")
    // fallback: getByPlaceholder("35")
    await page.locator("#hlc-age").click();
    // idle 8516ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 9997ms (no stable next locator — consider a manual waitFor)
  });
});
