import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T14:20:49.725Z
// Duration (active): 6584ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    // idle 1834ms (no stable next locator — consider a manual waitFor)
    // idle 1199ms (no stable next locator — consider a manual waitFor)
  });
});
