import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T16:36:16.832Z
// Duration (active): 411078ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Salaried" })
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(1)").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-age").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Age*\n                          \n                        \n                       " })
    // fallback: getByLabel("Age*\n                          \n                        \n                       ")
    // fallback: getByPlaceholder("35")
    await page.locator("#hlc-age").click();
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Monthly income*\n                        \n                      \n                " })
    // fallback: getByLabel("Monthly income*\n                        \n                      \n                ")
    // fallback: getByPlaceholder("1,00,000")
    await page.locator("#hlc-monthly-income").click();
    await page.locator("#hlc-age").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Age*\n                          \n                        \n                       " })
    // fallback: getByLabel("Age*\n                          \n                        \n                       ")
    // fallback: getByPlaceholder("35")
    await page.locator("#hlc-age").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Monthly income*\n                        \n                      \n                " })
    // fallback: getByLabel("Monthly income*\n                        \n                      \n                ")
    // fallback: getByPlaceholder("1,00,000")
    await page.locator("#hlc-monthly-income").click();
    // idle 9720ms (no stable next locator — consider a manual waitFor)
    // idle 10003ms (no stable next locator — consider a manual waitFor)
    // idle 8020ms (no stable next locator — consider a manual waitFor)
    // idle 8001ms (no stable next locator — consider a manual waitFor)
    // idle 9997ms (no stable next locator — consider a manual waitFor)
    // idle 8003ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 9982ms (no stable next locator — consider a manual waitFor)
    // idle 8017ms (no stable next locator — consider a manual waitFor)
    // idle 7984ms (no stable next locator — consider a manual waitFor)
    // idle 8015ms (no stable next locator — consider a manual waitFor)
    // idle 7999ms (no stable next locator — consider a manual waitFor)
    // idle 7994ms (no stable next locator — consider a manual waitFor)
    // idle 8004ms (no stable next locator — consider a manual waitFor)
    // idle 7996ms (no stable next locator — consider a manual waitFor)
    // idle 10002ms (no stable next locator — consider a manual waitFor)
    // idle 10000ms (no stable next locator — consider a manual waitFor)
    // idle 8004ms (no stable next locator — consider a manual waitFor)
    // idle 8003ms (no stable next locator — consider a manual waitFor)
    // idle 7997ms (no stable next locator — consider a manual waitFor)
    // idle 7997ms (no stable next locator — consider a manual waitFor)
    // idle 8004ms (no stable next locator — consider a manual waitFor)
    // idle 9999ms (no stable next locator — consider a manual waitFor)
    // idle 9986ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 9993ms (no stable next locator — consider a manual waitFor)
    // idle 8002ms (no stable next locator — consider a manual waitFor)
    // idle 7980ms (no stable next locator — consider a manual waitFor)
    // idle 8019ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 4461ms (no stable next locator — consider a manual waitFor)
    // idle 5526ms (no stable next locator — consider a manual waitFor)
  });
});
