import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T19:01:37.835Z
// Duration (active): 395148ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Open note for mark °" })
    await page.locator("th#hlc-th-rateChangeChargeDisplay > span > span > button").click();
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").click();
    await page.locator("details#hlc-charge-note-overdue-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-overdue-charge > summary > span > svg").click();
    await page.locator("details#hlc-charge-note-emi-bounce-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-emi-bounce-charge > summary > span > svg").click();
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg > path").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg > path").click();
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").waitFor({ state: 'visible' });
    await page.locator("details#hlc-charge-note-rate-change-charge > summary > span > svg").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg > path").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg > path").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg > path").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg > path").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg > path").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg > path").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(33) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg > path").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(3) > summary > span > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(3) > summary > span > span").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(5) > summary > span > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(5) > summary > span > span").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(5) > div > div > details:nth-of-type(1) > summary > span > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(5) > div > div > details:nth-of-type(1) > summary > span > span").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(1) > summary > span > span").click();
    await page.locator("div#hlc-drawer-body > details:nth-of-type(3) > summary > span > span").waitFor({ state: 'visible' });
    await page.locator("div#hlc-drawer-body > details:nth-of-type(3) > summary > span > span").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Top-up" })
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > div > button:nth-of-type(2)").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > span").click();
    // fallback: getByRole("checkbox", { name: "Women applicant" })
    // fallback: getByLabel("Women applicant")
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > input").click();
    // fallback: getByRole("checkbox", { name: "Women applicant" })
    // fallback: getByLabel("Women applicant")
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(2) > div > label:nth-of-type(1) > input").fill("on");
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Regular" })
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > div > button:nth-of-type(1)").click();
    // idle 2764ms (no stable next locator — consider a manual waitFor)
    // idle 1101ms (no stable next locator — consider a manual waitFor)
    // idle 4182ms (no stable next locator — consider a manual waitFor)
    // idle 7967ms (no stable next locator — consider a manual waitFor)
    // idle 8033ms (no stable next locator — consider a manual waitFor)
    // idle 8002ms (no stable next locator — consider a manual waitFor)
    // idle 8003ms (no stable next locator — consider a manual waitFor)
    // idle 7992ms (no stable next locator — consider a manual waitFor)
    // idle 8008ms (no stable next locator — consider a manual waitFor)
    // idle 8010ms (no stable next locator — consider a manual waitFor)
    // idle 7977ms (no stable next locator — consider a manual waitFor)
    // idle 2267ms (no stable next locator — consider a manual waitFor)
    // idle 2803ms (no stable next locator — consider a manual waitFor)
    // idle 1935ms (no stable next locator — consider a manual waitFor)
    // idle 2708ms (no stable next locator — consider a manual waitFor)
    // idle 2373ms (no stable next locator — consider a manual waitFor)
    // idle 2948ms (no stable next locator — consider a manual waitFor)
    // idle 6601ms (no stable next locator — consider a manual waitFor)
    // idle 1007ms (no stable next locator — consider a manual waitFor)
  });
});
