import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T17:52:41.328Z
// Duration (active): 545258ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").click();
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").fill("60,00,000");
    await page.locator("#hlc-property-value").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Property agreement value*\n                        \n                      \n      " })
    // fallback: getByLabel("Property agreement value*\n                        \n                      \n      ")
    // fallback: getByPlaceholder("62,50,000")
    await page.locator("#hlc-property-value").fill("60,00,000");
    // fallback: getByRole("main")
    await page.locator("main").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Regular" })
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(2) > div > button:nth-of-type(1)").click();
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-bank").click();
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").click();
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("tab", { name: "Charges" })
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").click();
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    // fallback: getByRole("tab", { name: "Other charges" })
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").click();
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("tab", { name: "Overview" })
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(1)").click();
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("tab", { name: "Charges" })
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(2)").click();
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").waitFor({ state: 'visible' });
    // fallback: getByRole("tab", { name: "Other charges" })
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(3)").click();
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("tab", { name: "Overview" })
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(1)").click();
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("tab", { name: "Overview" })
    await page.locator("section#hlc-results-shell > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div:nth-of-type(1) > div > button:nth-of-type(1)").click();
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").click();
    await page.locator("#hlc-edit-inputs").waitFor({ state: 'visible' });
    await page.locator("#hlc-edit-inputs").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Edit inputs" })
    await page.locator("#hlc-edit-inputs").click();
    await page.locator("button#hlc-edit-inputs > svg").waitFor({ state: 'visible' });
    await page.locator("button#hlc-edit-inputs > svg").waitFor({ state: 'visible' });
    await page.locator("button#hlc-edit-inputs > svg").waitFor({ state: 'visible' });
    await page.locator("button#hlc-edit-inputs > svg").click();
    await page.locator("main > div").waitFor({ state: 'visible' });
    await page.locator("main > div").waitFor({ state: 'visible' });
    await page.locator("main > div").waitFor({ state: 'visible' });
    await page.locator("main > div").click();
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").click();
    // idle 8678ms (no stable next locator — consider a manual waitFor)
  });
});
