import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T16:43:16.850Z
// Duration (active): 530676ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Self-employed" })
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(4) > div > div:nth-of-type(1) > div > button:nth-of-type(2)").click();
    // idle 9973ms (no stable next locator — consider a manual waitFor)
    // idle 7996ms (no stable next locator — consider a manual waitFor)
    // idle 8002ms (no stable next locator — consider a manual waitFor)
    // idle 8003ms (no stable next locator — consider a manual waitFor)
    // idle 9996ms (no stable next locator — consider a manual waitFor)
    // idle 8001ms (no stable next locator — consider a manual waitFor)
    // idle 9995ms (no stable next locator — consider a manual waitFor)
    // idle 8005ms (no stable next locator — consider a manual waitFor)
    // idle 8004ms (no stable next locator — consider a manual waitFor)
    // idle 9999ms (no stable next locator — consider a manual waitFor)
    // idle 9997ms (no stable next locator — consider a manual waitFor)
    // idle 8002ms (no stable next locator — consider a manual waitFor)
    // idle 9999ms (no stable next locator — consider a manual waitFor)
    // idle 10001ms (no stable next locator — consider a manual waitFor)
    // idle 7991ms (no stable next locator — consider a manual waitFor)
    // idle 10005ms (no stable next locator — consider a manual waitFor)
    // idle 8004ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 7999ms (no stable next locator — consider a manual waitFor)
    // idle 8003ms (no stable next locator — consider a manual waitFor)
    // idle 7994ms (no stable next locator — consider a manual waitFor)
    // idle 8004ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 7991ms (no stable next locator — consider a manual waitFor)
    // idle 10007ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 7985ms (no stable next locator — consider a manual waitFor)
    // idle 8009ms (no stable next locator — consider a manual waitFor)
    // idle 10008ms (no stable next locator — consider a manual waitFor)
    // idle 7997ms (no stable next locator — consider a manual waitFor)
    // idle 8002ms (no stable next locator — consider a manual waitFor)
    // idle 7991ms (no stable next locator — consider a manual waitFor)
    // idle 10008ms (no stable next locator — consider a manual waitFor)
    // idle 10002ms (no stable next locator — consider a manual waitFor)
    // idle 7984ms (no stable next locator — consider a manual waitFor)
    // idle 8013ms (no stable next locator — consider a manual waitFor)
    // idle 7987ms (no stable next locator — consider a manual waitFor)
    // idle 8011ms (no stable next locator — consider a manual waitFor)
    // idle 8003ms (no stable next locator — consider a manual waitFor)
    // idle 10001ms (no stable next locator — consider a manual waitFor)
    // idle 8001ms (no stable next locator — consider a manual waitFor)
    // idle 10001ms (no stable next locator — consider a manual waitFor)
    // idle 9994ms (no stable next locator — consider a manual waitFor)
    // idle 10003ms (no stable next locator — consider a manual waitFor)
    // idle 9985ms (no stable next locator — consider a manual waitFor)
  });
});
