import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T13:59:20.405Z
// Duration (active): 546835ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").click();
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").click();
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div > p:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div > p:nth-of-type(1)").click();
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div").click();
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div").click();
    // fallback: getByRole("heading")
    await page.locator("#home-lead-title").click();
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-zero-title > span:nth-of-type(1) > span:nth-of-type(1)").click();
    // idle 8208ms (no stable next locator — consider a manual waitFor)
    // idle 8036ms (no stable next locator — consider a manual waitFor)
    // idle 9969ms (no stable next locator — consider a manual waitFor)
    // idle 7998ms (no stable next locator — consider a manual waitFor)
    // idle 10000ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 9995ms (no stable next locator — consider a manual waitFor)
    // idle 7989ms (no stable next locator — consider a manual waitFor)
    // idle 8009ms (no stable next locator — consider a manual waitFor)
    // idle 9143ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 7999ms (no stable next locator — consider a manual waitFor)
    // idle 8003ms (no stable next locator — consider a manual waitFor)
    // idle 10001ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 9999ms (no stable next locator — consider a manual waitFor)
    // idle 8032ms (no stable next locator — consider a manual waitFor)
    // idle 7968ms (no stable next locator — consider a manual waitFor)
    // idle 7997ms (no stable next locator — consider a manual waitFor)
    // idle 8005ms (no stable next locator — consider a manual waitFor)
    // idle 9977ms (no stable next locator — consider a manual waitFor)
    // idle 8004ms (no stable next locator — consider a manual waitFor)
    // idle 9997ms (no stable next locator — consider a manual waitFor)
    // idle 8003ms (no stable next locator — consider a manual waitFor)
  });
});
