import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T18:02:07.502Z
// Duration (active): 555269ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(1) > div > div > div:nth-of-type(2) > button > span:nth-of-type(2) > svg").click();
    await page.locator("#hlc-drawer-close").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Close" })
    await page.locator("#hlc-drawer-close").click();
    await page.locator("th#hlc-th-effectiveRoiPct > span > span:nth-of-type(1) > svg > path").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-effectiveRoiPct > span > span:nth-of-type(1) > svg > path").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-effectiveRoiPct > span > span:nth-of-type(1) > svg > path").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-effectiveRoiPct > span > span:nth-of-type(1) > svg > path").click();
    await page.locator("th#hlc-th-effectiveRoiPct > span").click();
    await page.locator("#hlc-th-loanAmount").waitFor({ state: 'visible' });
    await page.locator("#hlc-th-loanAmount").click();
    await page.locator("th#hlc-th-loanAmount > span > span:nth-of-type(2) > svg").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-loanAmount > span > span:nth-of-type(2) > svg").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-loanAmount > span > span:nth-of-type(2) > svg").click();
    await page.locator("th#hlc-th-tenureLabel > span > span:nth-of-type(2) > svg").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-tenureLabel > span > span:nth-of-type(2) > svg").click();
    await page.locator("th#hlc-th-tenureLabel > span > span:nth-of-type(2) > svg").click();
    await page.locator("th#hlc-th-emi > span").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-emi > span").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-emi > span").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-emi > span").click();
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").waitFor({ state: 'visible' });
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Show how emi for Punjab National Bank was calculated" })
    await page.locator("tbody#hlc-compare-body > tr:nth-of-type(1) > td:nth-of-type(5) > button").click();
    await page.locator("#hlc-drawer-backdrop").waitFor({ state: 'visible' });
    await page.locator("#hlc-drawer-backdrop").click();
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2) > path").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2) > path").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2) > path").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2) > path").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2) > path").click();
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").click();
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div").click();
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    // fallback: getByRole("main")
    await page.locator("main").click();
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(4) > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Floating" })
    await page.locator("aside#hlc-filters-panel > div:nth-of-type(3) > fieldset:nth-of-type(4) > div > button:nth-of-type(1)").click();
    await page.locator("button#hlc-show-more > span").waitFor({ state: 'visible' });
    await page.locator("button#hlc-show-more > span").waitFor({ state: 'visible' });
    await page.locator("button#hlc-show-more > span").waitFor({ state: 'visible' });
    await page.locator("button#hlc-show-more > span").click();
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("th#hlc-th-bank > div > button > svg:nth-of-type(2)").click();
    // fallback: getByRole("button", { name: "Apply once to 33 banks" })
    await Promise.all([
      page.waitForURL("http://localhost:8765/pages/apply.html"),
      page.locator("#hlc-apply-btn").click(),
    ]);
    // unknown event kind: landmark_snapshot
    // idle 2890ms (no stable next locator — consider a manual waitFor)
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/explore-banks-html.png" });
    // idle 9523ms (no stable next locator — consider a manual waitFor)
    // idle 10020ms (no stable next locator — consider a manual waitFor)
    // idle 8018ms (no stable next locator — consider a manual waitFor)
    // idle 7994ms (no stable next locator — consider a manual waitFor)
    // idle 10002ms (no stable next locator — consider a manual waitFor)
    // idle 9998ms (no stable next locator — consider a manual waitFor)
    // idle 7997ms (no stable next locator — consider a manual waitFor)
    // idle 8001ms (no stable next locator — consider a manual waitFor)
    // idle 8010ms (no stable next locator — consider a manual waitFor)
    // idle 9999ms (no stable next locator — consider a manual waitFor)
    // idle 7990ms (no stable next locator — consider a manual waitFor)
    // idle 7979ms (no stable next locator — consider a manual waitFor)
    // idle 7991ms (no stable next locator — consider a manual waitFor)
    // idle 8054ms (no stable next locator — consider a manual waitFor)
    // idle 7982ms (no stable next locator — consider a manual waitFor)
    // idle 7986ms (no stable next locator — consider a manual waitFor)
    // idle 7982ms (no stable next locator — consider a manual waitFor)
    // idle 8009ms (no stable next locator — consider a manual waitFor)
    // idle 7989ms (no stable next locator — consider a manual waitFor)
    // idle 8003ms (no stable next locator — consider a manual waitFor)
    // idle 10034ms (no stable next locator — consider a manual waitFor)
    // idle 10002ms (no stable next locator — consider a manual waitFor)
  });
});
