import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T15:55:21.859Z
// Duration (active): 539127ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > rect").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > rect").waitFor({ state: 'visible' });
    await page.locator("form#hlc-inputs > div:nth-of-type(1) > div:nth-of-type(3) > div > label:nth-of-type(2) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > rect").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    // idle 8476ms (no stable next locator — consider a manual waitFor)
    // idle 7947ms (no stable next locator — consider a manual waitFor)
    // idle 7998ms (no stable next locator — consider a manual waitFor)
    // idle 8033ms (no stable next locator — consider a manual waitFor)
    // idle 7987ms (no stable next locator — consider a manual waitFor)
    // idle 10000ms (no stable next locator — consider a manual waitFor)
    // idle 7999ms (no stable next locator — consider a manual waitFor)
    // idle 7998ms (no stable next locator — consider a manual waitFor)
    // idle 8037ms (no stable next locator — consider a manual waitFor)
    // idle 7967ms (no stable next locator — consider a manual waitFor)
    // idle 10032ms (no stable next locator — consider a manual waitFor)
    // idle 7967ms (no stable next locator — consider a manual waitFor)
    // idle 10036ms (no stable next locator — consider a manual waitFor)
    // idle 7996ms (no stable next locator — consider a manual waitFor)
    // idle 9966ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 10000ms (no stable next locator — consider a manual waitFor)
    // idle 8033ms (no stable next locator — consider a manual waitFor)
    // idle 7997ms (no stable next locator — consider a manual waitFor)
    // idle 9968ms (no stable next locator — consider a manual waitFor)
    // idle 10031ms (no stable next locator — consider a manual waitFor)
    // idle 7974ms (no stable next locator — consider a manual waitFor)
  });
});
