import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T14:30:27.912Z
// Duration (active): 522367ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("h2#home-clear-title > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-clear-title > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-clear-title > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("h2#home-clear-title > span:nth-of-type(1)").click();
    await page.locator("main > div > section:nth-of-type(2) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(2) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(2) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(2) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(2) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(2) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(2) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(2) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(2) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(2) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(2) > div > div > div > p > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(2) > div > div > div > p > span:nth-of-type(2)").click();
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(4) > div > div > div > p > span:nth-of-type(1)").click();
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-1 > span:nth-of-type(2)").click();
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").click();
    // idle 1966ms (no stable next locator — consider a manual waitFor)
    // idle 7936ms (no stable next locator — consider a manual waitFor)
    // idle 8001ms (no stable next locator — consider a manual waitFor)
    // idle 3962ms (no stable next locator — consider a manual waitFor)
    // idle 2899ms (no stable next locator — consider a manual waitFor)
    // idle 1131ms (no stable next locator — consider a manual waitFor)
    // idle 8002ms (no stable next locator — consider a manual waitFor)
    // idle 10007ms (no stable next locator — consider a manual waitFor)
    // idle 7992ms (no stable next locator — consider a manual waitFor)
    // idle 8006ms (no stable next locator — consider a manual waitFor)
    // idle 8001ms (no stable next locator — consider a manual waitFor)
  });
});
