import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T17:01:14.381Z
// Duration (active): 528390ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    await page.locator("main").waitFor({ state: 'visible' });
    // fallback: getByRole("main")
    await page.locator("main").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-cibil").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "CIBIL score*\n                          \n                        \n               " })
    // fallback: getByLabel("CIBIL score*\n                          \n                        \n               ")
    // fallback: getByPlaceholder("780")
    await page.locator("#hlc-cibil").click();
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    await page.locator("#hlc-monthly-income").waitFor({ state: 'visible' });
    // fallback: getByRole("textbox", { name: "Monthly income*\n                        \n                      \n                " })
    // fallback: getByLabel("Monthly income*\n                        \n                      \n                ")
    // fallback: getByPlaceholder("1,00,000")
    await page.locator("#hlc-monthly-income").click();
    // idle 9084ms (no stable next locator — consider a manual waitFor)
    // idle 9976ms (no stable next locator — consider a manual waitFor)
    // idle 8015ms (no stable next locator — consider a manual waitFor)
    // idle 8004ms (no stable next locator — consider a manual waitFor)
    // idle 2363ms (no stable next locator — consider a manual waitFor)
    // idle 1633ms (no stable next locator — consider a manual waitFor)
    // idle 1568ms (no stable next locator — consider a manual waitFor)
    // idle 2407ms (no stable next locator — consider a manual waitFor)
    // idle 8031ms (no stable next locator — consider a manual waitFor)
    // idle 7999ms (no stable next locator — consider a manual waitFor)
    // idle 9970ms (no stable next locator — consider a manual waitFor)
    // idle 8054ms (no stable next locator — consider a manual waitFor)
    // idle 10000ms (no stable next locator — consider a manual waitFor)
    // idle 9970ms (no stable next locator — consider a manual waitFor)
    // idle 8030ms (no stable next locator — consider a manual waitFor)
    // idle 9964ms (no stable next locator — consider a manual waitFor)
    // idle 8035ms (no stable next locator — consider a manual waitFor)
    // idle 9964ms (no stable next locator — consider a manual waitFor)
    // idle 8037ms (no stable next locator — consider a manual waitFor)
    // idle 9995ms (no stable next locator — consider a manual waitFor)
    // idle 8006ms (no stable next locator — consider a manual waitFor)
    // idle 7998ms (no stable next locator — consider a manual waitFor)
    // idle 9967ms (no stable next locator — consider a manual waitFor)
    // idle 8033ms (no stable next locator — consider a manual waitFor)
    // idle 10002ms (no stable next locator — consider a manual waitFor)
    // idle 7999ms (no stable next locator — consider a manual waitFor)
  });
});
