import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T17:43:51.324Z
// Duration (active): 518906ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/pages/explore-banks.html");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").waitFor({ state: 'visible' });
    await page.locator("details#hlc-form-more > summary > span > span:nth-of-type(1) > span").click();
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(1)").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "No" })
    await page.locator("div#hlc-coapplicant-row > div:nth-of-type(1) > div > div > button:nth-of-type(1)").click();
    await page.locator("#hlc-coapplicant").fill("no");
    await page.getByRole("combobox", { name: "Share of credit card limits counted as monthly load" }).waitFor({ state: 'visible' });
    await page.getByRole("combobox", { name: "Share of credit card limits counted as monthly load" }).waitFor({ state: 'visible' });
    await page.getByRole("combobox", { name: "Share of credit card limits counted as monthly load" }).click();
    await page.locator("div#hlc-form-more-panel > div > div:nth-of-type(1) > div > span > span > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-form-more-panel > div > div:nth-of-type(1) > div > span > span > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("div#hlc-form-more-panel > div > div:nth-of-type(1) > div > span > span > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("div#hlc-form-more-panel > div > div:nth-of-type(1) > div > span > span > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("div#hlc-form-more-panel > div > label:nth-of-type(3) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-form-more-panel > div > label:nth-of-type(3) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("div#hlc-form-more-panel > div > label:nth-of-type(3) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("div#hlc-form-more-panel > div > label:nth-of-type(3) > span:nth-of-type(1) > span > span:nth-of-type(2) > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("main > div > div > div").waitFor({ state: 'visible' });
    await page.locator("main > div > div > div").click();
    await page.locator("div#hlc-form-more-panel > div > label:nth-of-type(1) > span:nth-of-type(1) > span > span > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-form-more-panel > div > label:nth-of-type(1) > span:nth-of-type(1) > span > span > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-form-more-panel > div > label:nth-of-type(1) > span:nth-of-type(1) > span > span > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-form-more-panel > div > label:nth-of-type(1) > span:nth-of-type(1) > span > span > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-form-more-panel > div > label:nth-of-type(1) > span:nth-of-type(1) > span > span > button > span > svg > circle:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("div#hlc-form-more-panel > div > label:nth-of-type(1) > span:nth-of-type(1) > span > span > button > span > svg > circle:nth-of-type(1)").click();
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").waitFor({ state: 'visible' });
    await page.locator("#hlc-coapplicant-row").click();
    // idle 9028ms (no stable next locator — consider a manual waitFor)
    // idle 7995ms (no stable next locator — consider a manual waitFor)
    // idle 5747ms (no stable next locator — consider a manual waitFor)
    // idle 1679ms (no stable next locator — consider a manual waitFor)
    // idle 2918ms (no stable next locator — consider a manual waitFor)
    // TODO: tab switch not auto-translated; manual adjustment needed
    // idle 2590ms (no stable next locator — consider a manual waitFor)
    // unknown event kind: landmark_snapshot
    // idle 1145ms (no stable next locator — consider a manual waitFor)
    // unknown event kind: landmark_snapshot
    await page.goto("https://www.google.com/search?q=cognitive+load&oq=cognitive+loa&gs_lcrp=***&sourceid=chrome&source=chrome.ob&ie=UTF-8&sei=fKaAaoatCIyQnesPlO-92Qo");
    await page.screenshot({ path: "screenshots/search.png" });
    // unknown event kind: landmark_snapshot
    // idle 6059ms (no stable next locator — consider a manual waitFor)
    // TODO: tab switch not auto-translated; manual adjustment needed
    // unknown event kind: landmark_snapshot
    // idle 1101ms (no stable next locator — consider a manual waitFor)
    // TODO: tab switch not auto-translated; manual adjustment needed
    // unknown event kind: landmark_snapshot
    // TODO: tab switch not auto-translated; manual adjustment needed
    // unknown event kind: landmark_snapshot
    // idle 9584ms (no stable next locator — consider a manual waitFor)
    // idle 7975ms (no stable next locator — consider a manual waitFor)
    // idle 8023ms (no stable next locator — consider a manual waitFor)
    // idle 8003ms (no stable next locator — consider a manual waitFor)
    // idle 9972ms (no stable next locator — consider a manual waitFor)
    // idle 8026ms (no stable next locator — consider a manual waitFor)
    // idle 7998ms (no stable next locator — consider a manual waitFor)
    // idle 10004ms (no stable next locator — consider a manual waitFor)
    // idle 9975ms (no stable next locator — consider a manual waitFor)
    // idle 8024ms (no stable next locator — consider a manual waitFor)
    // idle 9976ms (no stable next locator — consider a manual waitFor)
    // idle 8023ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 8003ms (no stable next locator — consider a manual waitFor)
    // idle 7998ms (no stable next locator — consider a manual waitFor)
    // idle 9998ms (no stable next locator — consider a manual waitFor)
    // idle 9978ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 8027ms (no stable next locator — consider a manual waitFor)
    // idle 7975ms (no stable next locator — consider a manual waitFor)
    // idle 8024ms (no stable next locator — consider a manual waitFor)
    // idle 7998ms (no stable next locator — consider a manual waitFor)
    // idle 9976ms (no stable next locator — consider a manual waitFor)
    // idle 8001ms (no stable next locator — consider a manual waitFor)
  });
});
