import { test, expect } from '@playwright/test';

// Auto-generated by workbooks-recorder from bundle: recorded session (workbooks-recording/2.2)
// Recorded: 2026-08-15T14:39:23.871Z
// Duration (active): 536089ms

test("recorded session", async ({ page }) => {
  await test.step("recorded session", async () => {
    await page.goto("http://localhost:8765/");
    await page.screenshot({ path: "screenshots/recorded-session-start.png" });
    // unknown event kind: landmark_snapshot
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div > p:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div > p:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div > p:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("main > div > section:nth-of-type(1) > div > div > div > div > p:nth-of-type(1)").click();
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").click();
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").click();
    await page.locator("button#home-built-trigger-3 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-3 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-3 > span:nth-of-type(1)").click();
    await page.locator("button#home-built-trigger-4 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-4 > span:nth-of-type(1)").click();
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-0 > span:nth-of-type(1)").click();
    await page.locator("button#home-built-trigger-4 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-4 > span:nth-of-type(1)").waitFor({ state: 'visible' });
    await page.locator("button#home-built-trigger-4 > span:nth-of-type(1)").click();
    await page.locator("main > section:nth-of-type(5) > div > div > button").waitFor({ state: 'visible' });
    await page.locator("main > section:nth-of-type(5) > div > div > button").waitFor({ state: 'visible' });
    await page.locator("main > section:nth-of-type(5) > div > div > button").waitFor({ state: 'visible' });
    await page.locator("main > section:nth-of-type(5) > div > div > button").waitFor({ state: 'visible' });
    await page.locator("main > section:nth-of-type(5) > div > div > button").waitFor({ state: 'visible' });
    await page.locator("main > section:nth-of-type(5) > div > div > button").waitFor({ state: 'visible' });
    await page.locator("main > section:nth-of-type(5) > div > div > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Play" })
    await page.locator("main > section:nth-of-type(5) > div > div > button").click();
    await page.locator("main > section:nth-of-type(5) > div > div > button").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Pause" })
    await page.locator("main > section:nth-of-type(5) > div > div > button").click();
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    await page.locator("#home-built-trigger-4").waitFor({ state: 'visible' });
    // fallback: getByRole("button", { name: "Help toward what you need" })
    await page.locator("#home-built-trigger-4").click();
    // idle 1794ms (no stable next locator — consider a manual waitFor)
    // idle 4735ms (no stable next locator — consider a manual waitFor)
    // idle 2854ms (no stable next locator — consider a manual waitFor)
    // idle 1714ms (no stable next locator — consider a manual waitFor)
    // idle 6307ms (no stable next locator — consider a manual waitFor)
    // idle 10004ms (no stable next locator — consider a manual waitFor)
    // idle 7989ms (no stable next locator — consider a manual waitFor)
    // idle 2798ms (no stable next locator — consider a manual waitFor)
    // idle 1732ms (no stable next locator — consider a manual waitFor)
    // idle 3461ms (no stable next locator — consider a manual waitFor)
    // idle 6407ms (no stable next locator — consider a manual waitFor)
    // idle 1596ms (no stable next locator — consider a manual waitFor)
    // idle 2336ms (no stable next locator — consider a manual waitFor)
    // idle 7659ms (no stable next locator — consider a manual waitFor)
    // idle 4709ms (no stable next locator — consider a manual waitFor)
    // idle 3263ms (no stable next locator — consider a manual waitFor)
    // idle 6169ms (no stable next locator — consider a manual waitFor)
    // idle 1867ms (no stable next locator — consider a manual waitFor)
    // idle 7972ms (no stable next locator — consider a manual waitFor)
    // idle 7995ms (no stable next locator — consider a manual waitFor)
    // idle 1434ms (no stable next locator — consider a manual waitFor)
    // idle 1498ms (no stable next locator — consider a manual waitFor)
    // idle 4457ms (no stable next locator — consider a manual waitFor)
    // idle 3828ms (no stable next locator — consider a manual waitFor)
    // idle 4178ms (no stable next locator — consider a manual waitFor)
    // idle 7997ms (no stable next locator — consider a manual waitFor)
    // idle 7984ms (no stable next locator — consider a manual waitFor)
    // idle 10016ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 8000ms (no stable next locator — consider a manual waitFor)
    // idle 7982ms (no stable next locator — consider a manual waitFor)
    // idle 10010ms (no stable next locator — consider a manual waitFor)
    // idle 7999ms (no stable next locator — consider a manual waitFor)
    // idle 7995ms (no stable next locator — consider a manual waitFor)
    // idle 8003ms (no stable next locator — consider a manual waitFor)
    // idle 8005ms (no stable next locator — consider a manual waitFor)
    // idle 8006ms (no stable next locator — consider a manual waitFor)
    // idle 9975ms (no stable next locator — consider a manual waitFor)
    // idle 4564ms (no stable next locator — consider a manual waitFor)
    // idle 3419ms (no stable next locator — consider a manual waitFor)
    // idle 10004ms (no stable next locator — consider a manual waitFor)
    // idle 8005ms (no stable next locator — consider a manual waitFor)
    // idle 7996ms (no stable next locator — consider a manual waitFor)
    // idle 8002ms (no stable next locator — consider a manual waitFor)
  });
});
